export const SERIF = "Georgia, 'Times New Roman', serif";
export const SANS = "'Helvetica Neue', Helvetica, Arial, sans-serif";

export const GLOBAL_CSS = `
  * { box-sizing: border-box; -webkit-tap-highlight-color: transparent; }
  body { margin: 0; }
  input, button, select { font-family: inherit; }
  @keyframes rise { from { opacity: 0; transform: translateY(8px); } to { opacity: 1; transform: none; } }
  @keyframes pulse { 0%,100% { opacity: 1; } 50% { opacity: 0.4; } }
  button:active { transform: scale(0.97); }
  ::-webkit-scrollbar { width: 0; height: 0; }
`;

export const styles = {
  page: {
    minHeight: "100vh",
    background: "radial-gradient(120% 80% at 50% 0%, #1a2238 0%, #121626 45%, #0c0e18 100%)",
    color: "#ece3d0", fontFamily: SANS, padding: "20px 16px 96px",
    display: "flex", flexDirection: "column", gap: 16, maxWidth: 560, margin: "0 auto",
  },
  kicker: { fontSize: 10, letterSpacing: 3, color: "#bfa46a" },
  bigTitle: { fontFamily: SERIF, fontSize: 44, fontWeight: 400, margin: "6px 0 0", fontStyle: "italic", color: "#f3ead4" },
  disclaimer: { fontSize: 11, lineHeight: 1.6, color: "#6f758c", textAlign: "center" },

  setupWrap: { display: "flex", flexDirection: "column", gap: 10, marginTop: 20, animation: "rise 0.5s ease both" },
  setupSub: { color: "#9aa0b5", fontSize: 14, marginTop: 4, marginBottom: 10 },
  inputBig: { background: "rgba(0,0,0,0.25)", border: "1px solid rgba(191,164,106,0.35)", borderRadius: 12, padding: "14px 14px", color: "#ece3d0", fontSize: 16, outline: "none", marginBottom: 6 },
  primaryBtn: { marginTop: 12, background: "#bfa46a", border: "none", color: "#15182a", borderRadius: 12, padding: "15px", fontSize: 16, fontWeight: 700, cursor: "pointer" },
  ghostBtn: { background: "none", border: "1px solid rgba(191,164,106,0.4)", color: "#bfa46a", borderRadius: 12, padding: "14px", fontSize: 15, cursor: "pointer" },
  linkBtn: { background: "none", border: "none", color: "#bfa46a", fontSize: 13, cursor: "pointer", textDecoration: "underline" },

  codeBox: { fontFamily: SERIF, fontSize: 38, letterSpacing: 8, color: "#f3ead4", textAlign: "center", background: "rgba(0,0,0,0.3)", border: "1px dashed rgba(191,164,106,0.5)", borderRadius: 14, padding: "18px", margin: "4px 0" },
  shareRow: { display: "flex", gap: 8, justifyContent: "center", flexWrap: "wrap" },

  feedV: { background: "rgba(0,0,0,0.3)", border: "1px solid rgba(191,164,106,0.25)", borderRadius: 12, padding: "8px 12px" },
  feedVHead: { display: "flex", alignItems: "center", gap: 6, marginBottom: 5 },
  feedDot: { width: 8, height: 8, borderRadius: 99, background: "#d9533b", flexShrink: 0, animation: "pulse 1.5s infinite" },
  feedVTitle: { fontSize: 9, letterSpacing: 2, color: "#d9533b" },
  feedVEmpty: { fontSize: 11, color: "#6f758c", fontStyle: "italic", padding: "2px 0" },
  feedVList: { display: "flex", flexDirection: "column", maxHeight: 78, overflowY: "auto" },
  feedVRow: { display: "flex", alignItems: "center", gap: 7, padding: "3px 0", borderBottom: "1px solid rgba(255,255,255,0.04)" },
  feedVIcon: { fontSize: 13, flexShrink: 0 },
  feedVText: { fontSize: 12, color: "#ece3d0", flex: 1, lineHeight: 1.25, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
  feedVAgo: { fontSize: 10, color: "#6f758c", flexShrink: 0 },
  feedVChat: { color: "#bfa46a", fontStyle: "italic" },
  feedChatPreview: { display: "flex", alignItems: "center", gap: 8, background: "rgba(191,164,106,0.1)", border: "1px solid rgba(191,164,106,0.25)", borderRadius: 8, padding: "6px 10px", marginBottom: 8 },
  feedChatIcon: { fontSize: 14, flexShrink: 0 },
  feedChatPrevText: { fontSize: 12, color: "#ece3d0", lineHeight: 1.3 },

  liveHeader: { textAlign: "center", display: "flex", flexDirection: "column", gap: 6 },
  headerRow: { display: "flex", alignItems: "center", justifyContent: "space-between" },
  gearBtn: { background: "rgba(255,255,255,0.06)", border: "1px solid rgba(191,164,106,0.3)", color: "#bfa46a", borderRadius: 99, padding: "5px 12px", fontSize: 12, cursor: "pointer" },
  eventTitleRow: { display: "flex", alignItems: "center", gap: 6 },
  themeMotif: { fontSize: 14 },
  liveStat: { fontSize: 13, color: "#9aa0b5" },

  tabBarFixed: { position: "fixed", left: 0, right: 0, bottom: 0, background: "rgba(10,12,20,0.92)", borderTop: "1px solid rgba(191,164,106,0.25)", backdropFilter: "blur(8px)", padding: "6px 12px calc(6px + env(safe-area-inset-bottom))", zIndex: 40 },
  tabBarInner: { display: "flex", gap: 6, maxWidth: 560, margin: "0 auto" },
  tab: { flex: 1, background: "none", border: "1px solid transparent", borderRadius: 10, padding: "6px 4px", color: "#9aa0b5", fontSize: 13, fontWeight: 600, cursor: "pointer", position: "relative", display: "flex", flexDirection: "column", alignItems: "center", gap: 2 },
  tabOn: { background: "rgba(255,255,255,0.06)", border: "1px solid" },
  tabIcon: { fontSize: 18 },
  tabName: { fontSize: 10, letterSpacing: 0.5 },
  tabBadge: { position: "absolute", top: 0, right: "50%", marginRight: -22, background: "#d9533b", color: "#fff", fontSize: 9, fontWeight: 700, borderRadius: 99, padding: "1px 5px", minWidth: 14 },
  emptyState: { textAlign: "center", color: "#9aa0b5", fontSize: 14, padding: "40px 20px", fontStyle: "italic" },

  lbWrap: { background: "rgba(255,255,255,0.03)", border: "1px solid rgba(191,164,106,0.22)", borderRadius: 14, padding: 14, display: "flex", flexDirection: "column", gap: 4 },
  lbTitle: { fontFamily: SERIF, fontSize: 16, fontStyle: "italic", color: "#f3ead4", marginBottom: 6 },
  lbRow: { display: "flex", alignItems: "center", gap: 12, padding: "8px 10px", borderRadius: 10 },
  lbRank: { fontSize: 16, width: 26, textAlign: "center", flexShrink: 0, color: "#9aa0b5" },
  lbName: { flex: 1, display: "flex", flexDirection: "column", gap: 1 },
  lbDesc: { fontSize: 11 },
  lbRight: { textAlign: "right", display: "flex", flexDirection: "column" },
  lbCount: { fontFamily: SERIF, fontSize: 22, lineHeight: 1 },
  lbBac: { fontSize: 10, color: "#6f758c" },

  groupWrap: { background: "rgba(255,255,255,0.03)", border: "1px solid rgba(191,164,106,0.22)", borderRadius: 14, padding: 14 },
  groupTitle: { fontFamily: SERIF, fontSize: 15, fontStyle: "italic", color: "#f3ead4", marginBottom: 10 },
  groupGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 },
  groupCell: { background: "rgba(0,0,0,0.2)", borderRadius: 10, padding: "10px 12px" },
  groupBig: { fontFamily: SERIF, fontSize: 18, color: "#f3ead4" },
  groupLabel: { fontSize: 11, color: "#9aa0b5", marginTop: 2 },

  barList: { display: "flex", flexDirection: "column", gap: 8 },
  barRow: { display: "flex", alignItems: "center", gap: 10 },
  barLabel: { fontSize: 13, color: "#cdd2e0", width: 92, flexShrink: 0 },
  barTrack: { flex: 1, height: 14, background: "rgba(255,255,255,0.06)", borderRadius: 99, overflow: "hidden" },
  barFill: { height: "100%", background: "linear-gradient(90deg,#bfa46a,#e8c95a)", borderRadius: 99, transition: "width 0.5s ease" },
  barCount: { fontSize: 13, color: "#bfa46a", fontWeight: 600, width: 22, textAlign: "right", flexShrink: 0 },

  cards: { display: "flex", flexDirection: "column", gap: 14 },
  card: { background: "linear-gradient(180deg, rgba(255,255,255,0.05), rgba(255,255,255,0.02))", border: "1px solid rgba(191,164,106,0.25)", borderRadius: 16, padding: 16, animation: "rise 0.4s ease both" },
  cardTop: { display: "flex", justifyContent: "space-between", alignItems: "flex-start" },
  name: { fontFamily: SERIF, fontSize: 22, color: "#f3ead4", display: "flex", alignItems: "center", gap: 6 },
  hostTag: { fontSize: 8, letterSpacing: 1, color: "#15182a", background: "#bfa46a", borderRadius: 4, padding: "2px 5px" },
  expandCaret: { color: "#bfa46a", fontSize: 15 },
  bodyline: { fontSize: 11, color: "#8a90a8", marginTop: 2 },
  editBtn: { background: "none", border: "none", color: "#bfa46a", fontSize: 11, marginLeft: 8, cursor: "pointer", textDecoration: "underline", padding: 0 },
  vomitTag: { color: "#8aa86a", fontSize: 11 },
  bacBlock: { textAlign: "right" },
  bacWord: { fontFamily: SERIF, fontSize: 16, fontWeight: 600 },
  bacNum: { fontSize: 11, color: "#8a90a8", marginTop: 2 },
  trendArrow: { fontWeight: 700, fontSize: 13 },
  meterTrack: { height: 6, background: "rgba(255,255,255,0.08)", borderRadius: 99, margin: "12px 0", overflow: "hidden" },
  meterFill: { height: "100%", borderRadius: 99, transition: "width 0.5s ease, background 0.5s" },
  countRow: { display: "flex", alignItems: "baseline", gap: 8, flexWrap: "wrap" },
  bigCount: { fontFamily: SERIF, fontSize: 34, color: "#f3ead4", lineHeight: 1 },
  countLabel: { fontSize: 13, color: "#9aa0b5" },
  paceChip: { fontSize: 12, color: "#9ab87a", border: "1px solid rgba(154,184,122,0.35)", borderRadius: 99, padding: "3px 10px" },
  vomitMini: { background: "rgba(154,184,122,0.12)", border: "1px solid rgba(154,184,122,0.3)", borderRadius: 8, fontSize: 15, cursor: "pointer", padding: "2px 7px", lineHeight: 1 },
  undo: { marginLeft: "auto", background: "none", border: "none", color: "#8a90a8", fontSize: 12, cursor: "pointer" },
  tallyRow: { display: "flex", gap: 12, marginTop: 10, fontSize: 13, color: "#cdd2e0" },
  drinkBtns: { display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 6, marginTop: 14 },
  drinkBtn: { display: "flex", flexDirection: "column", alignItems: "center", gap: 3, padding: "9px 2px", background: "rgba(191,164,106,0.1)", border: "1px solid rgba(191,164,106,0.3)", borderRadius: 10, color: "#ece3d0", cursor: "pointer" },
  drinkEmoji: { fontSize: 18 },
  drinkLabel: { fontSize: 9, color: "#bfa46a" },

  quickWrap: { background: "rgba(255,255,255,0.03)", border: "1px solid rgba(191,164,106,0.22)", borderRadius: 14, padding: 12, display: "flex", flexDirection: "column", gap: 8 },
  quickTitle: { fontSize: 11, letterSpacing: 1.5, color: "#bfa46a", marginBottom: 2 },
  quickRow: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" },
  quickInfo: { display: "flex", flexDirection: "column", minWidth: 70, cursor: "pointer" },
  quickName: { fontSize: 14, color: "#f3ead4", fontWeight: 600 },
  quickMeta: { fontSize: 10, color: "#9aa0b5" },
  quickBtns: { display: "flex", gap: 4, marginLeft: "auto", alignItems: "center", flexWrap: "wrap" },
  quickBtn: { background: "rgba(191,164,106,0.12)", border: "1px solid rgba(191,164,106,0.3)", borderRadius: 8, fontSize: 16, cursor: "pointer", padding: "5px 7px", lineHeight: 1 },
  quickVomit: { background: "rgba(154,184,122,0.12)", border: "1px solid rgba(154,184,122,0.3)", borderRadius: 8, fontSize: 14, cursor: "pointer", padding: "5px 7px", lineHeight: 1 },
  quickEdit: { background: "none", border: "1px solid rgba(255,255,255,0.15)", borderRadius: 8, fontSize: 14, color: "#9aa0b5", cursor: "pointer", padding: "5px 9px", lineHeight: 1 },

  statsPanel: { marginTop: 12, padding: "12px 14px", background: "rgba(0,0,0,0.2)", border: "1px solid rgba(191,164,106,0.18)", borderRadius: 10 },
  statRow: { display: "flex", justifyContent: "space-between", fontSize: 13, padding: "4px 0" },
  statKey: { color: "#9aa0b5" },
  statVal: { color: "#ece3d0", fontWeight: 600 },
  statDivider: { height: 1, background: "rgba(191,164,106,0.18)", margin: "8px 0" },
  logHeader: { fontSize: 11, color: "#bfa46a", fontStyle: "italic", marginBottom: 8 },
  logList: { display: "flex", flexDirection: "column", gap: 8 },
  logEntryCol: { display: "flex", flexDirection: "column", gap: 6 },
  logEntry: { display: "flex", alignItems: "center", gap: 8 },
  logTime: { fontSize: 11, color: "#6f758c", width: 58, flexShrink: 0 },
  logType: { fontSize: 13, color: "#ece3d0" },
  logVomit: { fontSize: 13, color: "#9ab87a" },
  logSizeBadge: { fontSize: 10, color: "#9aa0b5", border: "1px solid rgba(255,255,255,0.12)", borderRadius: 6, padding: "1px 6px" },
  logEditBtn: { marginLeft: "auto", background: "none", border: "none", color: "#bfa46a", fontSize: 12, cursor: "pointer", textDecoration: "underline", padding: "0 4px" },
  logDelete: { background: "none", border: "none", color: "#d9533b", fontSize: 14, cursor: "pointer", padding: "0 4px" },
  logControls: { display: "flex", justifyContent: "space-between", gap: 8, paddingLeft: 58, flexWrap: "wrap" },
  logChipRow: { display: "flex", gap: 4 },
  logChip: { background: "rgba(0,0,0,0.25)", border: "1px solid rgba(191,164,106,0.25)", borderRadius: 7, width: 30, height: 28, fontSize: 14, cursor: "pointer", padding: 0 },
  logChipOn: { background: "rgba(191,164,106,0.35)", borderColor: "#bfa46a" },
  logSize: { background: "rgba(0,0,0,0.25)", border: "1px solid rgba(191,164,106,0.25)", borderRadius: 7, width: 28, height: 28, color: "#ece3d0", fontSize: 12, cursor: "pointer", padding: 0 },

  graphWrap: { background: "rgba(255,255,255,0.03)", border: "1px solid rgba(191,164,106,0.22)", borderRadius: 14, padding: 14 },
  graphHead: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 8, flexWrap: "wrap", gap: 8 },
  graphTitle: { fontFamily: SERIF, fontSize: 16, color: "#f3ead4", fontStyle: "italic" },
  metricToggle: { display: "flex", gap: 4 },
  metricBtn: { background: "rgba(0,0,0,0.25)", border: "1px solid rgba(191,164,106,0.25)", borderRadius: 8, padding: "4px 10px", color: "#9aa0b5", fontSize: 11, cursor: "pointer" },
  metricOn: { background: "#bfa46a", color: "#15182a", borderColor: "#bfa46a", fontWeight: 600 },
  legend: { display: "flex", flexWrap: "wrap", gap: "6px 12px", marginTop: 10, justifyContent: "center" },
  legendItem: { fontSize: 11, color: "#cdd2e0", display: "flex", alignItems: "center", gap: 4 },
  legendDot: { width: 9, height: 9, borderRadius: 99, display: "inline-block", flexShrink: 0 },
  scrubHint: { fontSize: 11, color: "#6f758c", textAlign: "center", marginTop: 8, fontStyle: "italic" },
  tip: { position: "absolute", top: 6, background: "rgba(12,14,24,0.95)", border: "1px solid rgba(191,164,106,0.5)", borderRadius: 10, padding: "8px 10px", pointerEvents: "none", minWidth: 110, boxShadow: "0 6px 18px rgba(0,0,0,0.5)", zIndex: 5 },
  tipTime: { fontFamily: SERIF, fontSize: 13, color: "#f3ead4", fontStyle: "italic", marginBottom: 6, borderBottom: "1px solid rgba(191,164,106,0.25)", paddingBottom: 4 },
  tipRow: { display: "flex", alignItems: "center", gap: 6, fontSize: 12, padding: "1px 0" },
  tipName: { color: "#cdd2e0", flex: 1 },
  tipVal: { color: "#bfa46a", fontWeight: 600 },

  addPerson: { background: "none", border: "1px dashed rgba(191,164,106,0.45)", color: "#bfa46a", borderRadius: 12, padding: "14px", fontSize: 14, cursor: "pointer", fontFamily: SERIF, fontStyle: "italic" },
  endBtn: { background: "linear-gradient(100deg,#3a2a5a,#5a2e4a)", border: "1px solid rgba(191,164,106,0.4)", color: "#f3ead4", borderRadius: 12, padding: "15px", fontSize: 15, fontWeight: 600, cursor: "pointer", fontFamily: SERIF },
  reset: { background: "none", border: "none", color: "#5a6078", fontSize: 12, cursor: "pointer", textDecoration: "underline" },

  chatWrap: { background: "rgba(255,255,255,0.03)", border: "1px solid rgba(191,164,106,0.22)", borderRadius: 14, padding: 14 },
  chatHead: { display: "flex", justifyContent: "space-between", alignItems: "center", cursor: "pointer" },
  chatTitle: { fontFamily: SERIF, fontSize: 16, color: "#f3ead4", fontStyle: "italic" },
  chatCount: { fontSize: 11, color: "#15182a", background: "#bfa46a", borderRadius: 99, padding: "1px 7px", marginLeft: 6 },
  chatList: { display: "flex", flexDirection: "column", gap: 6, maxHeight: 360, overflowY: "auto", margin: "10px 0" },
  chatEmpty: { fontSize: 12, color: "#6f758c", fontStyle: "italic" },
  chatMsg: { display: "flex", alignItems: "baseline", gap: 6, fontSize: 13 },
  chatAuthor: { color: "#bfa46a", fontWeight: 600, flexShrink: 0 },
  chatText: { color: "#ece3d0", flex: 1, wordBreak: "break-word" },
  chatTime: { color: "#6f758c", fontSize: 10, flexShrink: 0 },
  chatDel: { background: "none", border: "none", color: "#5a6078", fontSize: 12, cursor: "pointer", flexShrink: 0 },
  chatInputRow: { display: "flex", gap: 6, alignItems: "center" },
  chatAsYou: { fontSize: 13, color: "#bfa46a", fontWeight: 600, flexShrink: 0 },
  chatInput: { flex: 1, background: "rgba(0,0,0,0.3)", border: "1px solid rgba(191,164,106,0.3)", borderRadius: 8, color: "#ece3d0", fontSize: 14, padding: "8px 10px", outline: "none" },
  chatSend: { background: "#bfa46a", border: "none", color: "#15182a", borderRadius: 8, padding: "8px 14px", fontSize: 13, fontWeight: 600, cursor: "pointer" },
  chatNote: { fontSize: 10, color: "#6f758c", marginTop: 8, fontStyle: "italic" },

  settingBlock: { background: "rgba(255,255,255,0.03)", border: "1px solid rgba(191,164,106,0.2)", borderRadius: 14, padding: 14 },
  settingTitle: { fontFamily: SERIF, fontSize: 15, fontStyle: "italic", color: "#f3ead4", marginBottom: 10 },
  settingRow: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "5px 0" },
  settingLabel: { fontSize: 14, color: "#cdd2e0" },
  settingHint: { fontSize: 11, color: "#6f758c", marginTop: 8, fontStyle: "italic" },
  numInput: { background: "rgba(0,0,0,0.3)", border: "1px solid rgba(191,164,106,0.3)", borderRadius: 8, color: "#ece3d0", fontSize: 14, padding: "6px 10px", width: 80, textAlign: "right", outline: "none" },
  select: { background: "rgba(0,0,0,0.3)", border: "1px solid rgba(191,164,106,0.3)", borderRadius: 8, color: "#ece3d0", fontSize: 14, padding: "7px 10px" },
  themeGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8 },
  themeChip: { borderRadius: 10, padding: "16px 10px", fontSize: 13, cursor: "pointer", textAlign: "center" },
  qrPlaceholder: { display: "flex", gap: 12, alignItems: "center" },
  qrText: { fontSize: 12, color: "#9aa0b5", lineHeight: 1.5 },
  miniDelete: { background: "none", border: "1px solid rgba(192,57,43,0.4)", color: "#d9533b", borderRadius: 6, fontSize: 11, cursor: "pointer", padding: "3px 7px" },
  addDrinkRow: { marginTop: 12, display: "flex", flexDirection: "column", gap: 8, borderTop: "1px solid rgba(191,164,106,0.15)", paddingTop: 12 },
  emojiPickRow: { display: "flex", flexWrap: "wrap", gap: 4 },
  emojiPick: { background: "rgba(0,0,0,0.25)", border: "1px solid rgba(191,164,106,0.25)", borderRadius: 7, fontSize: 16, cursor: "pointer", padding: "4px 7px" },
  emojiPickOn: { background: "rgba(191,164,106,0.35)", borderColor: "#bfa46a" },

  form: { background: "rgba(255,255,255,0.04)", border: "1px solid rgba(191,164,106,0.3)", borderRadius: 16, padding: 16, display: "flex", flexDirection: "column", gap: 12 },
  input: { background: "rgba(0,0,0,0.25)", border: "1px solid rgba(191,164,106,0.3)", borderRadius: 10, padding: "10px 12px", color: "#ece3d0", fontSize: 15, outline: "none" },
  formRow: { display: "flex", alignItems: "center", gap: 10 },
  fieldLabel: { fontSize: 13, color: "#9aa0b5", width: 56 },
  toggle: { display: "flex", gap: 6 },
  toggleBtn: { background: "rgba(0,0,0,0.25)", border: "1px solid rgba(191,164,106,0.3)", borderRadius: 99, padding: "6px 16px", color: "#9aa0b5", fontSize: 13, cursor: "pointer", textTransform: "capitalize" },
  toggleOn: { background: "#bfa46a", color: "#15182a", borderColor: "#bfa46a" },
  formActions: { display: "flex", gap: 10, justifyContent: "flex-end", marginTop: 4 },
  cancelBtn: { background: "none", border: "1px solid rgba(255,255,255,0.15)", color: "#9aa0b5", borderRadius: 10, padding: "9px 18px", fontSize: 14, cursor: "pointer" },
  saveBtn: { background: "#bfa46a", border: "none", color: "#15182a", borderRadius: 10, padding: "9px 22px", fontSize: 14, fontWeight: 600, cursor: "pointer" },
  removeBtn: { background: "none", border: "1px solid rgba(192,57,43,0.5)", color: "#d9533b", borderRadius: 10, padding: "9px 16px", fontSize: 14, cursor: "pointer", marginRight: "auto" },
  dangerBtn: { background: "#c0392b", border: "none", color: "#fff", borderRadius: 10, padding: "9px 18px", fontSize: 14, fontWeight: 600, cursor: "pointer" },
  modalBg: { position: "fixed", inset: 0, background: "rgba(8,10,18,0.7)", display: "flex", alignItems: "center", justifyContent: "center", padding: 20, zIndex: 50 },
  modal: { background: "#1a1e30", border: "1px solid rgba(191,164,106,0.35)", borderRadius: 16, padding: 20, width: "100%", maxWidth: 360, display: "flex", flexDirection: "column", gap: 12 },
  modalTitle: { fontFamily: SERIF, fontSize: 20, color: "#f3ead4", fontStyle: "italic" },
  confirmText: { fontSize: 14, lineHeight: 1.6, color: "#cdd2e0", margin: 0 },

  wrappedTop: { textAlign: "center" },
  wrappedDots: { display: "flex", gap: 5, justifyContent: "center", marginBottom: 10 },
  wDot: { width: 18, height: 3, borderRadius: 99, background: "rgba(255,255,255,0.2)" },
  wDotOn: { background: "#bfa46a" },
  wrappedEvent: { fontSize: 11, letterSpacing: 2, color: "#9aa0b5" },
  wrappedSlide: { flex: 1, borderRadius: 20, padding: 28, display: "flex", flexDirection: "column", justifyContent: "center", gap: 12, cursor: "pointer", minHeight: 360, animation: "rise 0.4s ease both" },
  wKicker: { fontSize: 12, letterSpacing: 3, color: "rgba(255,255,255,0.7)" },
  wBig: { fontFamily: SERIF, fontSize: 52, fontWeight: 400, color: "#fff", lineHeight: 1.05, fontStyle: "italic" },
  wSub: { fontSize: 16, color: "rgba(255,255,255,0.85)", lineHeight: 1.4 },
  wList: { display: "flex", flexDirection: "column", gap: 8, marginTop: 8 },
  wListRow: { display: "flex", alignItems: "center", gap: 10, fontSize: 18, color: "#fff" },
  wListRank: { fontFamily: SERIF, fontStyle: "italic", color: "rgba(255,255,255,0.6)", width: 20 },
  wListName: { flex: 1 },
  wListVal: { fontWeight: 700 },
  wrappedNav: { display: "flex", justifyContent: "space-between", alignItems: "center", marginTop: 4 },
  wNavBtn: { background: "rgba(255,255,255,0.1)", border: "1px solid rgba(255,255,255,0.2)", color: "#f3ead4", borderRadius: 10, padding: "10px 18px", fontSize: 14, cursor: "pointer" },
  wrappedFooter: { display: "flex", gap: 8, justifyContent: "center", alignItems: "center", marginTop: 4 },
  dotSep: { color: "#5a6078" },

  histList: { display: "flex", flexDirection: "column", gap: 8, marginTop: 8 },
  histRow: { display: "flex", justifyContent: "space-between", alignItems: "center", background: "rgba(255,255,255,0.04)", border: "1px solid rgba(191,164,106,0.2)", borderRadius: 10, padding: "12px 14px", cursor: "pointer" },
  histName: { fontSize: 15, color: "#f3ead4" },
  histMeta: { fontSize: 11, color: "#9aa0b5", marginTop: 2 },
};
